export default {
    LOGIN: 'Login',
    LOGOUT: 'Log out',
    SIGNUP: 'Signup',
    EMAIL: 'Email',
    PASSWORD: 'Password',
    FORGETPASSWORD: 'Forgot Password',
    PHONENUMBER: 'Phone Number',
    DOB: 'D.O.B',
    MALE: 'MALE',
    FEMALE: 'FEMALE',
    OTHER: 'OTHER',
    CONFIRM_PASSWORD: 'Confirm password',
    GENDER: 'Gender',
    CITY: 'City',
    FIRSTNAME: 'First Name',
    LASTNAME: 'Last Name',
    LOCATION: 'Location',
    ADDRESS: 'Address',
    PINCODE: 'Pincode/Zipcode',
    GETSTARTED: 'Get Started',
    NEXT: 'Next',
    SUBMIT: 'Submit',
    DONE: 'Done',
    TERMS: 'Terms & Conditions',
    ENGLISH: 'English',
    HINDI: 'Hindi',
    PLOGIN: 'LOGIN WITH MOBILE',
    ENTER_YOUR_PHONE_NUMBER: 'Enter your phone number',
    ENTER_REQ_DIGIT_OTP: 'Enter the 4-digit code sent to you at',
    RESEND_OTP: 'Resend OTP',
    DID_NT_RECEVI_OTP: "Didn't Received OTP?",
    REQUES_FOR_OTP: 'Request for OTP',
    OTP_IN: '',
    OK: 'OK',
    SIGNUP_USING_SOCIAL: 'Sign up using your social account',
    SIGNIN_USING_SOCIAL: 'Sign in using your social account',
    BY_CLICK_SIGNUP: `By clicking "Sign Up", you agree to our `,
    OUR_TERM_CONDITIONS: 'Terms & Conditions ',
    AS_WELL_AS: 'as well as ',
    PRIVACY_POLICY: 'Privacy Policy',
    TO_AGREE: '', //for TERM_&CONDITION REQURIED FOR HINDI,
    PLS_ENTER_EMAIL: 'Please enter email',
    WELCOME_BACK: 'Welcome back!',
    PLS_ENTER_VALID_PHONE: 'Please enter valid phone number',
    CREATE_YOUR_ACCOUNT: 'Create your account!',
    ENTER_EMAIL_FOR_PWD_LINK:
      'Enter your email and we’ll send you. Instructions on how to reset your password.',
    PLS_ENTER_VALID_EMAIL: 'Please enter valid email',
    PLS_ENTER_VALID_OTP: 'Please enter valid OTP',
    PLS_UPLOAD_IMAGE: 'Please upload an image',
    PASSWORD_INCORRECT: 'Password is incorrect',
    PASSWORD_REQUIRES_SIX_DIGIT: 'Password requires minimum 6 characters',
    PASSWORD_CONFIRM_PWD_DIDNT_MATCH:
      "Password and confrim password didn't mateched",
    THANKS_FOR_INTEREST_COUNTRY:
      'Thanks for your interest. Our operations are currently only available within India. Looking forward to engaging with you in the near future.',
    YOU_ARE_READY_TO_GO: 'You are ready to go!',
    THAKS_FOR_ACCOUNT_CREATION:
      "Thanks for your time to create account with us.Before exploring the app please tell us more about yourself by giving answers of simple questions",
    PLEASE_SELECT_YOUR_LANGUAGE: 'Please select your language',
    CHECK_YOUR_EMAIL: 'Check your email',
    WE_HAVE_SENT_INSTRUCATION:
      "We've sent instructions on how to reset the password(also check the Spam)",
    CHOOSE_YOUR_LANGUAGE: 'Choose Your Preferred Language',
    OR: 'OR',
    SURVEY_FOR_YOU: 'SURVEY FOR YOU',
    BROWSE_SURVEY: 'Browse Surveys',
    REFER_A_FRIEND: 'Refer A Friend',
    WIN_REWARD: '& Win Rewards',
    EARNED_REWARD: 'Earned Rewards',
    HOME: 'Home',
    WALLET: 'Wallet',
    SURVEYS: 'Surveys',
    OFFER: 'Offer',
    MORE: 'More',
    FAQ: 'FAQ',
    CONTACT_US: 'Contact us',
    CONTACT_THROUGHT_PHONE: 'Contact through Phone',
    CONTACT_THROUGHT_Email: 'Contact through Email',
    TYPE_HERE: 'Type Here...',
    NOTIFICATION: 'Notifications',
    MY_WALLET: 'My Wallet',
    CASH: 'Cash',
    COUPONS: 'Coupons',
    POINTS: 'Points',
    TOTAL_COINS: 'Total Coins',
    REDEEM: 'Redeem',
    EXPIRES: 'Expires',
    DISCOUNT: 'DISCOUNT',
    TOTAL_POINTS: 'Total Points',
    ALL_SURVEY: 'All Surveys',
    HISTORY: 'History',
    LIVE: 'Live',
    INDUSTRY: 'Industry',
    DURATION: 'Survey Duration',
    REWARDS: 'Rewards',
    FILTER_SORTING: 'Filter and sorting',
    SEARCH: 'Search',
    CATEGORY: 'Category',
    OPEN: 'Open',
    CLOSED: 'Closed',
    COMPLETED: 'Completed',
    APPLY_FILTER: 'APPLY FILTER',
    CLEAR_FILER: 'Clear filter',
    STATUS: 'Status',
    USER_INFO: 'User Information',
    PHONE: 'Phone',
    COMPLETE_PROFILE_REWARD: 'Complete your profile \nAnd earn rewards',
    COMPLETE_PROFILE: 'COMPLETE PROFILE',
    SAVE: 'SAVE',
    NEW_SURVEY: 'New Survey',
    SUCCESSFULLY_COMPLETED: 'Successfully completed',
    POINTS_GET: ' Your survey has been answered \n      and you get',
    RESET_INSTRUCTIONS:
      'We’ve sent instructions on how to reset the \n    password (also check the Spam folder).',
    RESET_PASSWORD: 'Reset Password',
    ENTER_YOUR_NEW_PASSWORD:
      'Enter your new password and confirm new password for your DdipstiQ account.',
    YES: 'Yes',
    NO: 'No',
    LOGOUT: 'Logout',
    ARE_YOU_SURE_YOU_WANT_TO_LOGOUT: 'Are you sure you want to logout',
    ARE_YOU_SURE_YOU_WANT_TO_DEACTIVATE:
      'Are you sure you want to Deactivate your account',
    DEACTIVATE: 'Deactivate',
    NEW_PASSWORD: 'New Password',
    PLEASE_ENTER_PASSWORD: 'Please enter password',
    PLEASE_ENTER_NEW_PASS: 'Please enter new password',
    QUESTIONS: 'Questions',
    UNSATISFIED: 'UnSatisfied',
    SATISFIED: 'Satisfied',
    GREAT: 'Great',
    GOOD: 'Good',
    NEXT: 'Next',
    BACK: 'Back',
    COMPLETE: 'Complete',
    OFFER: 'Offers',
    FAQ: 'FAQ',
    ADD_REFERAL_CODE:"Add referal code",
    PLEASE_SELECT_AN_OPTION:"Please select an option",
    ENTER_TEXT:"Enter text",
    GETTING_STARTED:"GETTING STARTED",
    LOGIN_TO_YOUR_ACCOUNT:"Log in to your account",
    PROFILE:"PROFILE"
  };