export default {
    LOGIN: 'लॉग इन करें',
    LOGOUT: 'लॉग आउट',
    SIGNUP: 'साइन अप करें',
    EMAIL: 'ईमेल',
    PASSWORD: 'पासवर्ड',
    CONFIRM_PASSWORD:"पासवर्ड की पुष्टि कीजिये",
    CREATE_YOUR_ACCOUNT:"खुद को रजिस्टर करें!",
    FORGETPASSWORD: 'पासवर्ड भूल गए',
    PHONENUMBER: 'फ़ोन नंबर',
    FULLNAME: 'पूरा नाम',
    LOCATION: 'स्थान',
    ADDRESS: 'पता',
    INDUSTRY: 'उद्योग',
    DONE: 'किया हुआ',
    TERMS: 'नियम एवं शर्तें',
    ENGLISH: 'अंग्रेज़ी',
    HINDI: 'हिन्दी',
    LOGININTO: 'अपने खाते में लॉग इन करें',
    OR: 'या',
    Social: 'अपने सामाजिक खाते का उपयोग करके साइन अप करें',
    THANKS:
      'अपनी प्रोफ़ाइल सबमिट करने के लिए धन्यवाद। हम आप तक वापस आ रहे हैं जल्द ही।',
    REFRESH: 'ताज़ा करना',
    ENTEREMAIL:'अपना ईमेल दर्ज करें और हम आपको भेज देंगे। अपना पासवर्ड रीसेट करने के निर्देश।',
    CHECKMAIL: 'अपने ईमेल की जाँच करें',
    SENTMAIL:
      'हमने रीसेट करने के निर्देश भेज दिए हैं। \n पासवर्ड (Spam \n फ़ोल्डर की भी जाँच करें)).',
    OK: 'ठीक आहे',
    ENTER_NUMBER: 'अपना दूरभाष क्रमांक दर्ज करें',
    HOME: 'घर',
    SURVEY: 'सर्वेक्षण',
    SURVEYS: 'सर्वेक्षण',
    BILLING: 'बिलिंग',
    PACKAGE: 'पैकेज',
    INBOX: 'इनबॉक्स',
    VIEW: 'सभी को देखें',
    
    STATUS: 'स्थिति देखें',
    LAUNCH: 'नया लॉन्च करें',
    SURVEY_STATUS: 'सर्वेक्षण की स्थिति',
    LAUNCH_TITLE: 'कृपया हमें अपने राज्य की शोध समस्या लिखें',
    ADD_NEW: 'नया जोड़ो',
    PACKAGES: 'संकुल',
    CURRENT_PACKAGE: 'वर्तमान पैकेज',
    LEFT: '/10 सर्वेक्षण शेष हैं',
    HISTORY: 'इतिहास',
    NOTIFICATION: 'अधिसूचना',
    ALL_SURVEY: 'सभी सर्वेक्षण',
    
    ACTIVITIES: 'गतिविधियों',
    DOWNLOAD_REPORT: 'रिपोर्ट डाउनलोड करें',
    Color: 'रंग',
    MANAGE: 'प्रबंधित',
    DELETE: 'हटाएं',
    PAUSE: 'ठहराव',
    EDIT: 'संपादित करें',
    PROGRESS: 'प्रगति पट्टी',
    PIE: 'पाई चार्ट',
    LINE: 'पंक्ति चार्ट',
    AREA: 'क्षेत्र चार्ट',
    WORK: 'HOW IT WORKS?',
    SURVEY_PACKAGE: 'सर्वेक्षण पैकेज',
    PLAN:
      'एप्लिकेशन की सभी कार्यक्षमता को अनलॉक करने के लिए एक सदस्यता योजना चुनें',
    BUY_PACKAGE: 'पैकेज खरीदें',
    PROMOTIONAL: 'प्रोमोशनल ऑफ़र',
    CUSTOMIZE: 'पैकेज को कस्टमाइज़ करें',
    CUSTOMIZE_PACKAGE: 'अपने पैकेज को अनुकूलित करें',
    NUMBER_OF: 'सर्वेक्षणों की संख्या',
    SURVEY_DURATION: 'सर्वे की अवधि',
    NUMBER_RESPONSE: 'उत्तरदाताओं की संख्या',
    NUMBER_LANG: 'भाषाओं की संख्या',
    BOTH: 'दोनों',
    RESET: 'पासवर्ड रीसेट',
    ENTER_NEW:
      'अपना नया पासवर्ड दर्ज करें और अपने Ddipsitq खाते के लिए पासवर्ड की पुष्टि करें',
    READY: 'तुम जाने के लिए तैयार हो',
    RESET_DONE:
      "हमारे साथ खाता बनाने के लिए आपके समय के लिए धन्यवाद। अब यह मजेदार हिस्सा है, आइए ऐप को एक्सप्लोर करें",
    DEACTIVATE: 'निष्क्रिय करें',
    CHANGE_PASSWORD: 'पासवर्ड बदलें',
    USER_INFO: 'यूजर जानकारी',
    FIRST: 'पहला नाम',
    PHONE: 'फ़ोन',
    COMPANY: 'कंपनी',
    DESIGNATION: 'पद',
    SAVE: 'बचा ले',
    PINCODE: 'पिनकोड / ज़िपकोड',//hinidi are present from now
    GETSTARTED: 'शुरू हो जाओ',
    PLEASE_SELECT_YOUR_LANGUAGE:"कृपया अपनी भाषा चुनें",
    NEXT:"अगला",
    SUBMIT: 'प्रस्तुत',
    DONE: 'किया हुआ',
    TERMS: 'नियम एवं शर्तें',
    ENGLISH: 'अंग्रेज़ी',
    HINDI: 'हिन्दी',
    PLOGIN: 'मोबाइल के साथ लॉगिन करें',
    ENTER_YOUR_PHONE_NUMBER:"अपना दूरभाष क्रमांक दर्ज करें",
    ENTER_REQ_DIGIT_OTP:"आपको भेजा गया 4-अंकीय कोड दर्ज करें",
    RESEND_OTP:"ओटीपी पुनः भेजें",
    DID_NT_RECEVI_OTP:"क्या OTP प्राप्त नहीं हुआ?",
    REQUES_FOR_OTP:"OTP के लिए अनुरोध",
    OTP_IN:"",
    OK:"ठीक है",
    BY_CLICK_SIGNUP:`"साइन अप" पर क्लिक करके, आप हमारे लिए सहमत हैं `,
    OUR_TERM_CONDITIONS:"नियम एवं शर्तें",
    AS_WELL_AS:"साथ ही साथ ",
    PRIVACY_POLICY:"गोपनीयता नीति",
    TO_AGREE:"",//for TERM_&CONDITION REQURIED FOR HINDI,
    PLS_ENTER_EMAIL:"कृपया ईमेल दर्ज करें",
    PLS_ENTER_VALID_PHONE:"कृपया एक वैध नंबर डालें",
    ENTER_EMAIL_FOR_PWD_LINK:"अपना ईमेल दर्ज करें और हम आपको भेज देंगे। अपना पासवर्ड रीसेट करने के निर्देश।",
    PLS_ENTER_VALID_EMAIL:"कृपया वैध ईमेल दर्ज़ करें",
    PLS_ENTER_VALID_OTP:"कृपया मान्य OTP दर्ज करें",
    PLS_UPLOAD_IMAGE:"कृपया एक छवि अपलोड करें",
    PASSWORD_INCORRECT:"पासवर्ड गलत है",
    PASSWORD_REQUIRES_SIX_DIGIT:"पासवर्ड के लिए न्यूनतम 6 वर्णों की आवश्यकता होती है",
    PASSWORD_CONFIRM_PWD_DIDNT_MATCH:"पासवर्ड और कन्फर्म पासवर्ड मिट नहीं गए",
    THANKS_FOR_INTEREST_COUNTRY:"आपकी रुचि के लिए धन्यवाद। हमारे ऑपरेशन वर्तमान में केवल भारत में उपलब्ध हैं। निकट भविष्य में आपसे उलझने की आशा कर रहा है।",
    YOU_ARE_READY_TO_GO:"आप अनुप्रयोग का उपयोग करने के लिए तैयार हैं!",
    THAKS_FOR_ACCOUNT_CREATION:"हमारे साथ खाता बनाने के लिए आपके समय के लिए धन्यवाद। अब यह मजेदार हिस्सा है, आइए ऐप को एक्सप्लोर करें",
    ADD_REFERAL_CODE:"रेफरल कोड जोड़ें",
    WELCOME_BACK:"वापसी पर स्वागत है!",
    CHECK_YOUR_EMAIL:"अपने ईमेल की जाँच करें",
    WE_HAVE_SENT_INSTRUCATION:"हमने पासवर्ड रीसेट करने के निर्देश दिए हैं (स्पैम की जाँच भी करें)",
    PLEASE_ADD_QUESTION:"कृपया प्रश्न जोड़ें",
    PLEASE_ENTER_PASSWORD:"कृप्या पास्वर्ड भरो",
    PLEASE_ENTER_NEW_PASS:"कृपया नया पासवर्ड दर्ज करें",
    NEW_PASSWORD:"नया पासवर्ड",
    YES:"हाँ",
    NO:"नहीं",
    LOGOUT:"लॉग आउट",
    ARE_YOU_SURE_YOU_WANT_TO_LOGOUT:"क्या आप लॉग आउट करना चाहते हैं?",
    ARE_YOU_SURE_YOU_WANT_TO_DEACTIVATE:"क्या आप वाकई अपना खाता निष्क्रिय करना चाहते हैं?",
    DEACTIVATE:"निष्क्रिय करें",
    NOTIFICATIONS:"सूचनाएं",
    LIVE_SURVEY: 'लाइव सर्वेक्षण',
    LIVE_SURVEYS: 'लाइव सर्वेक्षण',
    PAST_SURVEYS: 'पूर्व सर्वेक्षण',
    SURVEYS_STATUS: 'सर्वे की स्थिति',
    QUESTIONS:"प्रशन",
    VIEW_QUESTIONS:"प्रश्न देखें",
    DURATION:"समयांतराल",
    FIRST_NAME:"पहला नाम",
    LAST_NAME:"उपनाम",
    RESPONDENTES:"उत्तरदाताओं",
    DAYS:"दिन",
    UPCOMING:"आगामी",
    ONGOING:'चल रही है',
    LEFT:'बाएं'
  };